"""
Vercel Python serverless function for Liaison physio-handoff PDF rendering.

Receives JSON content from the Liaison agent, renders a clean physio-doc HTML
template, converts to PDF via WeasyPrint, uploads to Supabase Storage, and
returns the storage path.

Locally `next dev` does NOT run Python — Liaison detects this and proceeds
with content_summary saved to the row, no PDF attached. On Vercel both
co-exist and Liaison's flow completes end-to-end.
"""

from http.server import BaseHTTPRequestHandler
import json
import os

try:
    from weasyprint import HTML  # type: ignore
except Exception:  # pragma: no cover
    HTML = None

try:
    from supabase import create_client  # type: ignore
except Exception:  # pragma: no cover
    create_client = None


SUPABASE_URL = os.environ.get("NEXT_PUBLIC_SUPABASE_URL")
SUPABASE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
BUCKET = "documents"


HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Physio handoff — Balance</title>
<style>
  @page {{ size: A4; margin: 24mm 22mm; }}
  body {{
    font-family: 'Inter', sans-serif;
    color: #2d2520;
    font-size: 11pt;
    line-height: 1.55;
  }}
  h1 {{
    font-family: 'Fraunces', serif;
    font-weight: 500;
    font-size: 24pt;
    margin: 0 0 4mm 0;
    color: #2d2520;
  }}
  h2 {{
    font-family: 'Fraunces', serif;
    font-weight: 500;
    font-size: 14pt;
    margin: 8mm 0 2mm 0;
    color: #6b9077;
  }}
  .meta {{
    color: #8a7f76;
    font-size: 10pt;
    margin-bottom: 8mm;
    border-bottom: 1px solid #e8e0d6;
    padding-bottom: 4mm;
  }}
  ul {{ margin: 0 0 4mm 4mm; padding: 0; }}
  li {{ margin: 0 0 2mm 0; }}
  .summary {{
    background: rgba(127, 167, 138, 0.08);
    border-radius: 6mm;
    padding: 4mm 5mm;
    margin-bottom: 4mm;
  }}
  .questions {{
    background: rgba(232, 195, 168, 0.10);
    border-radius: 6mm;
    padding: 4mm 5mm;
    margin: 2mm 0 4mm 0;
  }}
  .working {{
    background: rgba(127, 167, 138, 0.12);
    border-radius: 6mm;
    padding: 4mm 5mm;
    color: #2d2520;
    margin-top: 4mm;
  }}
  .footer {{
    color: #b8aea4;
    font-size: 9pt;
    margin-top: 12mm;
    border-top: 1px solid #e8e0d6;
    padding-top: 3mm;
  }}
</style>
</head>
<body>
  <h1>Physio handoff</h1>
  <div class="meta">
    Prepared for the appointment on {appointment_date} ·
    Generated by Balance care team ·
    {generated_at}
  </div>

  <div class="summary">{summary}</div>

  <h2>Posture trends</h2>
  <ul>{posture_items}</ul>

  <h2>Pain patterns</h2>
  <ul>{pain_items}</ul>

  <h2>Compliance with prescribed program</h2>
  <p>{compliance}</p>

  <h2>Questions worth asking</h2>
  <div class="questions"><ul>{question_items}</ul></div>

  <div class="working"><strong>What's working:</strong> {what_is_working}</div>

  <div class="footer">
    Balance is a movement coaching tool, not a diagnostic device.
    Measurements are estimated from webcam pose landmarks; Cobb angle and
    structural assessment remain the physio's source of truth.
  </div>
</body>
</html>
"""


def render_template(content: dict, appointment_at: str, generated_at: str) -> str:
    li = lambda items: "".join(f"<li>{escape(x)}</li>" for x in items)
    return HTML_TEMPLATE.format(
        appointment_date=escape(appointment_at),
        generated_at=escape(generated_at),
        summary=escape(content.get("summary", "")),
        posture_items=li(content.get("posture_trends", [])),
        pain_items=li(content.get("pain_patterns", [])),
        compliance=escape(content.get("compliance", "")),
        question_items=li(content.get("questions_for_physio", [])),
        what_is_working=escape(content.get("what_is_working", "")),
    )


def escape(s: str) -> str:
    if s is None:
        return ""
    return (
        str(s)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _bad_request(handler: BaseHTTPRequestHandler, message: str, status: int = 400):
    body = json.dumps({"error": message}).encode("utf-8")
    handler.send_response(status)
    handler.send_header("Content-Type", "application/json")
    handler.send_header("Content-Length", str(len(body)))
    handler.end_headers()
    handler.wfile.write(body)


class handler(BaseHTTPRequestHandler):
    def do_POST(self):  # noqa: N802
        try:
            length = int(self.headers.get("Content-Length", "0"))
            if length <= 0:
                return _bad_request(self, "empty body")
            payload = json.loads(self.rfile.read(length))

            content = payload.get("content")
            appointment_id = payload.get("appointmentId")
            if not content or not appointment_id:
                return _bad_request(self, "content and appointmentId are required")

            if HTML is None:
                return _bad_request(self, "weasyprint not installed", 500)
            if create_client is None or not SUPABASE_URL or not SUPABASE_KEY:
                return _bad_request(self, "supabase client not configured", 500)

            html_str = render_template(
                content,
                appointment_at=payload.get("appointment_at", "(date not provided)"),
                generated_at=payload.get("generated_at", ""),
            )
            pdf_bytes = HTML(string=html_str).write_pdf()
            if not pdf_bytes:
                return _bad_request(self, "pdf generation returned empty", 502)

            supabase = create_client(SUPABASE_URL, SUPABASE_KEY)
            storage_path = f"liaison/{appointment_id}.pdf"
            try:
                supabase.storage.from_(BUCKET).remove([storage_path])
            except Exception:
                pass
            supabase.storage.from_(BUCKET).upload(
                storage_path,
                pdf_bytes,
                {"content-type": "application/pdf", "upsert": "true"},
            )

            body = json.dumps({"pdfStoragePath": storage_path}).encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        except Exception as exc:  # noqa: BLE001
            _bad_request(self, f"pdf generation failed: {exc}", 500)
